### ISSUE TITLE
Implement the question history for the users

### ISSUE THREAD

**Issue by algarfer** [Arquisoft/wiq_es05b#109]
It is necessary for the application to have a history of games played, in order to satisfy the basic requirements.

It must be done:
- [ ] Backend (add error handle)
- [ ] Gateway integration
- [ ] Frontend design of the history
- [ ] Modify game view to work properly with the new server (maybe)
