### ISSUE TITLE
Finish history integration and change some game functionality

### ISSUE THREAD

**Issue by algarfer** [Arquisoft/wiq_es05b#121]
Currently, the game only saves the answered questions when a button is pressed.
Now the timer also starts even if the questions are not properly loaded.
Also there is a bug where the last question is not added to the total points in the frontend.

This changes should be implemented:
- [x] The timer should start when all the questions are in the webapp.
- [x] The app should send the answer petition when a button is pressed or when the time is finished
- [x] The backend should calculate the points of each question
- [x] The backend should return the points of the question
- [x] Endgame shouldnt be a route itself but the final view of the game
